name: Deploy the frontend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: setup Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./apps/web
        run: pnpm install

      - name: Build the project
        working-directory: ./apps/web
        run: pnpm build
